/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_sandbox;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Jahn
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        secondaryProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jtbToolBar = new javax.swing.JToolBar();
        jbNew = new javax.swing.JButton();
        jbOpen = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jbSaveAs = new javax.swing.JButton();
        jbMake = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jpAttributePane = new javax.swing.JPanel();
        jlCompName = new javax.swing.JLabel();
        jtfCompName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jlCompType = new javax.swing.JLabel();
        jcbCompType = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jlProperty = new javax.swing.JLabel();
        jlSize = new javax.swing.JLabel();
        jtfWidth = new javax.swing.JTextField();
        jlMul = new javax.swing.JLabel();
        jtfHeight = new javax.swing.JTextField();
        jlBG_Color = new javax.swing.JLabel();
        jtfBG_Red = new javax.swing.JTextField();
        jtfBG_Green = new javax.swing.JTextField();
        jtfBG_Blue = new javax.swing.JTextField();
        jbBG_Chooser = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jlLocation = new javax.swing.JLabel();
        jlLocation_X = new javax.swing.JLabel();
        jtfLocation_X = new javax.swing.JTextField();
        jlLocation_Y = new javax.swing.JLabel();
        jtfLocation_Y = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jlTextProperty = new javax.swing.JLabel();
        jlTextContent = new javax.swing.JLabel();
        jtfTextContent = new javax.swing.JTextField();
        jlTextSize = new javax.swing.JLabel();
        jsTextSizeSpinner = new javax.swing.JSpinner();
        jlText_Color = new javax.swing.JLabel();
        jtfText_Red = new javax.swing.JTextField();
        jtfText_Green = new javax.swing.JTextField();
        jtfText_Blue = new javax.swing.JTextField();
        jbApply = new javax.swing.JButton();
        jbText_Chooser = new javax.swing.JButton();
        jpEditorPane = new javax.swing.JPanel();
        jmbMenuBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiNew = new javax.swing.JMenuItem();
        jmiOpen = new javax.swing.JMenuItem();
        jmiSave = new javax.swing.JMenuItem();
        jmiSaveAs = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();
        jmCreateComponent = new javax.swing.JMenu();
        jmiCreateJLabel = new javax.swing.JMenuItem();
        jmiCreateJButton = new javax.swing.JMenuItem();
        jmiCreateTextField = new javax.swing.JMenuItem();
        jmiCreateTextArea = new javax.swing.JMenuItem();
        jmiDeleteComponent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbToolBar.setFloatable(false);
        jtbToolBar.setRollover(true);

        jbNew.setText("New");
        jbNew.setFocusable(false);
        jbNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });
        jtbToolBar.add(jbNew);

        jbOpen.setText("Open");
        jbOpen.setFocusable(false);
        jbOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbOpen);

        jbSave.setText("Save");
        jbSave.setFocusable(false);
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbSave);

        jbSaveAs.setText("SaveAs");
        jbSaveAs.setFocusable(false);
        jbSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbToolBar.add(jbSaveAs);

        jbMake.setText("Make");
        jbMake.setFocusable(false);
        jbMake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMake.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMakeActionPerformed(evt);
            }
        });
        jtbToolBar.add(jbMake);

        jbDelete.setText("Delete");
        jbDelete.setFocusable(false);
        jbDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jtbToolBar.add(jbDelete);

        jpAttributePane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlCompName.setText("ComponentName");

        jtfCompName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompNameActionPerformed(evt);
            }
        });

        jlCompType.setText("ComponentType");

        jcbCompType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Label", "Button", "Toggle Button", "Check Box" }));
        jcbCompType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCompTypeActionPerformed(evt);
            }
        });

        jlProperty.setText("Property");

        jlSize.setText("Width * Height");

        jtfWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWidthActionPerformed(evt);
            }
        });

        jlMul.setText("*");

        jtfHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHeightActionPerformed(evt);
            }
        });

        jlBG_Color.setText("Background Color");

        jtfBG_Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBG_RedActionPerformed(evt);
            }
        });

        jtfBG_Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBG_GreenActionPerformed(evt);
            }
        });

        jtfBG_Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBG_BlueActionPerformed(evt);
            }
        });

        jlLocation.setText("Location");

        jlLocation_X.setText("X :");

        jlLocation_Y.setText("Y :");

        jlTextProperty.setText("TextProperty");

        jlTextContent.setText("Content");

        jlTextSize.setText("Size");

        jlText_Color.setText("Color");

        jtfText_Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfText_RedActionPerformed(evt);
            }
        });

        jtfText_Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfText_GreenActionPerformed(evt);
            }
        });

        jtfText_Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfText_BlueActionPerformed(evt);
            }
        });

        jbApply.setText("Apply");
        jbApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAttributePaneLayout = new javax.swing.GroupLayout(jpAttributePane);
        jpAttributePane.setLayout(jpAttributePaneLayout);
        jpAttributePaneLayout.setHorizontalGroup(
            jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCompName)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAttributePaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbApply))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jcbCompType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jlCompName)
                    .addComponent(jlProperty)
                    .addComponent(jlLocation)
                    .addComponent(jlTextProperty)
                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBG_Color)
                            .addComponent(jlSize)
                            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                        .addComponent(jtfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlMul)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                        .addComponent(jtfBG_Red, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfBG_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfBG_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbBG_Chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jlCompType)
                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAttributePaneLayout.createSequentialGroup()
                                .addComponent(jlLocation_Y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfLocation_Y))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAttributePaneLayout.createSequentialGroup()
                                .addComponent(jlLocation_X)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfLocation_X, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator4)
                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTextContent)
                                    .addComponent(jlTextSize))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTextContent)
                                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                        .addComponent(jsTextSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                .addComponent(jlText_Color)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jtfText_Red, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfText_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfText_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbText_Chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpAttributePaneLayout.setVerticalGroup(
            jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCompName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jlCompType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCompType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jlProperty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlBG_Color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBG_Chooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfBG_Red, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfBG_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfBG_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLocation_X)
                    .addComponent(jtfLocation_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLocation_Y)
                    .addComponent(jtfLocation_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTextProperty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTextContent)
                    .addComponent(jtfTextContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTextSize)
                    .addComponent(jsTextSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlText_Color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                        .addGroup(jpAttributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfText_Red, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfText_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfText_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jbApply))
                    .addGroup(jpAttributePaneLayout.createSequentialGroup()
                        .addComponent(jbText_Chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpEditorPane.setBackground(new java.awt.Color(255, 255, 255));
        jpEditorPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpEditorPaneLayout = new javax.swing.GroupLayout(jpEditorPane);
        jpEditorPane.setLayout(jpEditorPaneLayout);
        jpEditorPaneLayout.setHorizontalGroup(
            jpEditorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jpEditorPaneLayout.setVerticalGroup(
            jpEditorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jmFile.setText("File");

        jmiNew.setText("New");
        jmiNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewActionPerformed(evt);
            }
        });
        jmFile.add(jmiNew);

        jmiOpen.setText("Open");
        jmiOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenActionPerformed(evt);
            }
        });
        jmFile.add(jmiOpen);

        jmiSave.setText("Save");
        jmFile.add(jmiSave);

        jmiSaveAs.setText("Save As");
        jmFile.add(jmiSaveAs);

        jmbMenuBar.add(jmFile);

        jmEdit.setText("Edit");

        jmCreateComponent.setText("Create Component");

        jmiCreateJLabel.setText("Create JLabel");
        jmiCreateJLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateJLabelActionPerformed(evt);
            }
        });
        jmCreateComponent.add(jmiCreateJLabel);

        jmiCreateJButton.setText("Create JButton");
        jmiCreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateJButtonActionPerformed(evt);
            }
        });
        jmCreateComponent.add(jmiCreateJButton);

        jmiCreateTextField.setText("Create JTextField");
        jmiCreateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateTextFieldActionPerformed(evt);
            }
        });
        jmCreateComponent.add(jmiCreateTextField);

        jmiCreateTextArea.setText("Create JTextArea");
        jmiCreateTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateTextAreaActionPerformed(evt);
            }
        });
        jmCreateComponent.add(jmiCreateTextArea);

        jmEdit.add(jmCreateComponent);

        jmiDeleteComponent.setText("Delete Component");
        jmEdit.add(jmiDeleteComponent);

        jmbMenuBar.add(jmEdit);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAttributePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEditorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAttributePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEditorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void secondaryProcess()
    {
        addMouseListener(new MouseAdapter()
        {
            @Override
            public void mousePressed(MouseEvent me)
            {
                requestFocusInWindow();
                System.out.println("Frame");
            }
        });
        jpEditorPane.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mousePressed(MouseEvent me)
            {
                requestFocusInWindow();
                System.out.println("EditorPane");
            }
        });
    }
    public enum Type
    {
        JLABEL, JBUTTON, JTEXT_FIELD, JTEXT_AREA
    }
    private void createNewComponent(JPanel ep, Type comp_type)
    {
        Component lastAdded = null;
        if (ep.getComponentCount() != 0)
        {
            lastAdded = ep.getComponent(ep.getComponentCount()-1);
        }
        GGgoComponent newComponent = null;
        String s = "Test String";
        switch (comp_type)
        {
            case JLABEL:
                newComponent = new GGgoComponent(new JLabel(s));
                break;
            case JBUTTON:
                newComponent = new GGgoComponent(new JButton(s));
                break;
            case JTEXT_FIELD:
                newComponent = new GGgoComponent(new JTextField(s));
                break;
            case JTEXT_AREA:
                newComponent = new GGgoComponent(new JTextArea(s));
                break;
        }
        newComponent.addFocusListener(new MyFocusListenr());
        ep.add(newComponent);
        Rectangle bounds = new Rectangle(0, 0, 100, 100);
        if (lastAdded != null)
        {
            bounds = lastAdded.getBounds();
        }
        bounds.translate(50, 50);
        newComponent.setBounds(bounds);
        ep.revalidate();
    }
    private void jbApplyActionPerformed(ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jcbCompTypeActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jtfWidthActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jtfHeightActionPerformed(ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jtfBG_RedActionPerformed(ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jtfBG_GreenActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jtfBG_BlueActionPerformed(ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jtfCompNameActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jtfText_RedActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jtfText_GreenActionPerformed(ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jtfText_BlueActionPerformed(ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jmiNewActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jmiCreateJLabelActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        createNewComponent(jpEditorPane, Type.JLABEL);
    }                                                

    private void jmiCreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        createNewComponent(jpEditorPane, Type.JBUTTON);
    }

    private void jmiCreateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        createNewComponent(jpEditorPane, Type.JTEXT_FIELD);
    }                                                

    private void jmiCreateTextAreaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        createNewComponent(jpEditorPane, Type.JTEXT_AREA);
    }                                                 

    private void jbMakeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        createNewComponent(jpEditorPane, Type.JBUTTON);
    }                                      

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(focused != null)
        {
            focused.getParent().remove(focused);
            focused = null;
            jpEditorPane.repaint();
            System.out.println("deleted");
        }
    }                                        

    private void jmiOpenActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    class MyFocusListenr implements FocusListener
    {
        @Override
        public void focusGained(FocusEvent fe)
        {
            focused = fe.getComponent();
            fe.getComponent().repaint();
            System.out.println("gained");
        }
        @Override
        public void focusLost(FocusEvent fe)
        {
            fe.getComponent().repaint();
            System.out.println("lost");
            if (fe.getOppositeComponent() != jbDelete)
            {
                focused = null;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // cursor component to indicate selected component
    private Component focused;

    // Variables declaration - do not modify                     
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbApply;
    private javax.swing.JButton jbBG_Chooser;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbMake;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbOpen;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSaveAs;
    private javax.swing.JButton jbText_Chooser;
    private javax.swing.JComboBox<String> jcbCompType;
    private javax.swing.JMenuItem jmiCreateTextArea;
    private javax.swing.JLabel jlBG_Color;
    private javax.swing.JLabel jlCompName;
    private javax.swing.JLabel jlCompType;
    private javax.swing.JLabel jlLocation;
    private javax.swing.JLabel jlLocation_X;
    private javax.swing.JLabel jlLocation_Y;
    private javax.swing.JLabel jlMul;
    private javax.swing.JLabel jlProperty;
    private javax.swing.JLabel jlSize;
    private javax.swing.JLabel jlTextContent;
    private javax.swing.JLabel jlTextProperty;
    private javax.swing.JLabel jlTextSize;
    private javax.swing.JLabel jlText_Color;
    private javax.swing.JMenu jmCreateComponent;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JMenuItem jmiCreateJButton;
    private javax.swing.JMenuItem jmiCreateJLabel;
    private javax.swing.JMenuItem jmiCreateTextField;
    private javax.swing.JMenuItem jmiDeleteComponent;
    private javax.swing.JMenuItem jmiNew;
    private javax.swing.JMenuItem jmiOpen;
    private javax.swing.JMenuItem jmiSave;
    private javax.swing.JMenuItem jmiSaveAs;
    private javax.swing.JPanel jpAttributePane;
    private javax.swing.JPanel jpEditorPane;
    private javax.swing.JSpinner jsTextSizeSpinner;
    private javax.swing.JToolBar jtbToolBar;
    private javax.swing.JTextField jtfBG_Blue;
    private javax.swing.JTextField jtfBG_Green;
    private javax.swing.JTextField jtfBG_Red;
    private javax.swing.JTextField jtfCompName;
    private javax.swing.JTextField jtfHeight;
    private javax.swing.JTextField jtfLocation_X;
    private javax.swing.JTextField jtfLocation_Y;
    private javax.swing.JTextField jtfTextContent;
    private javax.swing.JTextField jtfText_Blue;
    private javax.swing.JTextField jtfText_Green;
    private javax.swing.JTextField jtfText_Red;
    private javax.swing.JTextField jtfWidth;
    // End of variables declaration                   
}
